// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogpostDocumentDataSlicesSlice = TextBlockSlice;

/**
 * Content for Blogpost documents
 */
interface BlogpostDocumentData {
  /**
   * Name field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Author field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Featured Image field in *Blogpost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.featured_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Date Published field in *Blogpost*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.date_published
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_published: prismic.DateField;

  /**
   * Slice Zone field in *Blogpost*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogpostDocumentDataSlicesSlice> /**
   * Meta Title field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blogpost.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Blogpost*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blogpost.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Blogpost*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blogpost.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Blogpost document from Prismic
 *
 * - **API ID**: `blogpost`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogpostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogpostDocumentData>,
    "blogpost",
    Lang
  >;

type HomepageDocumentDataSlicesSlice =
  | GoogleMapsSectionSlice
  | PageHeroSlice
  | StatsSlice
  | TextBlockSlice
  | CheckImageContentSlice
  | ReusableCardSliceSlice
  | FullWidthQuoteSlice
  | FullWidthFeaturedSlice
  | RecommendedReadingSlice
  | FrequentAnsweredQuestionsSlice
  | ContactInfoSectionSlice
  | ContactFormSectionSlice
  | QuoteContentSlice
  | BlogIndexSlice
  | FeaturesSlice
  | ReusuableContentSlice
  | HeadingContentSlice
  | ImageContentSlice
  | TestimonialsSlice
  | FeaturedSlice
  | SolutionsSlice
  | NewsletterSubSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type PageDocumentDataSlicesSlice =
  | QuoteContentSlice
  | BlogIndexSlice
  | ContactInfoSectionSlice
  | GoogleMapsSectionSlice
  | ContactFormSectionSlice
  | TextBlockSlice
  | RecommendedReadingSlice
  | StatsSlice
  | CheckImageContentSlice
  | FullWidthQuoteSlice
  | FullWidthFeaturedSlice
  | ReusableCardSliceSlice
  | FrequentAnsweredQuestionsSlice
  | TestimonialsSlice
  | ReusuableContentSlice
  | ImageContentSlice
  | SolutionsSlice
  | PageHeroSlice
  | HeroSlice
  | NewsletterSubSlice
  | HeadingContentSlice
  | FeaturesSlice
  | FeaturedSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Name field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

type ServiceDocumentDataSlicesSlice =
  | GoogleMapsSectionSlice
  | QuoteContentSlice
  | ReusableTableSliceSlice
  | ContactInfoSectionSlice
  | ContactFormSectionSlice
  | BlogIndexSlice
  | FeaturedSlice
  | FeaturesSlice
  | CheckImageContentSlice
  | HeadingContentSlice
  | HeroSlice
  | FullWidthQuoteSlice
  | FullWidthFeaturedSlice
  | FrequentAnsweredQuestionsSlice
  | ImageContentSlice
  | RecommendedReadingSlice
  | PageHeroSlice
  | NewsletterSubSlice
  | ReusableCardSliceSlice
  | ReusuableContentSlice
  | SolutionsSlice
  | TextBlockSlice
  | TestimonialsSlice
  | StatsSlice;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
  /**
   * Name field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Slice Zone field in *Service*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: service.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ServiceDocumentDataSlicesSlice> /**
   * Meta Title field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: service.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Service*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: service.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Service*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ServiceDocumentData>,
    "service",
    Lang
  >;

export type AllDocumentTypes =
  | BlogpostDocument
  | HomepageDocument
  | PageDocument
  | ServiceDocument;

/**
 * Default variation for BlogIndex Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogIndexSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *BlogIndex*
 */
type BlogIndexSliceVariation = BlogIndexSliceDefault;

/**
 * BlogIndex Shared Slice
 *
 * - **API ID**: `blog_index`
 * - **Description**: BlogIndex
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogIndexSlice = prismic.SharedSlice<
  "blog_index",
  BlogIndexSliceVariation
>;

/**
 * Primary content in *CheckImageContent → Primary*
 */
export interface CheckImageContentSliceDefaultPrimary {
  /**
   * Featured Image field in *CheckImageContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: check_image_content.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Tag field in *CheckImageContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: check_image_content.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Heading field in *CheckImageContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: check_image_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *CheckImageContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: check_image_content.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Right Image field in *CheckImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: check_image_content.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  right_image: prismic.BooleanField;

  /**
   * Green Background field in *CheckImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: check_image_content.primary.green_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  green_background: prismic.BooleanField;
}

/**
 * Primary content in *CheckImageContent → Items*
 */
export interface CheckImageContentSliceDefaultItem {
  /**
   * Check Content field in *CheckImageContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: check_image_content.items[].check_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  check_content: prismic.RichTextField;
}

/**
 * Default variation for CheckImageContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CheckImageContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CheckImageContentSliceDefaultPrimary>,
  Simplify<CheckImageContentSliceDefaultItem>
>;

/**
 * Slice variation for *CheckImageContent*
 */
type CheckImageContentSliceVariation = CheckImageContentSliceDefault;

/**
 * CheckImageContent Shared Slice
 *
 * - **API ID**: `check_image_content`
 * - **Description**: CheckImageContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CheckImageContentSlice = prismic.SharedSlice<
  "check_image_content",
  CheckImageContentSliceVariation
>;

/**
 * Default variation for ContactFormSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactFormSection*
 */
type ContactFormSectionSliceVariation = ContactFormSectionSliceDefault;

/**
 * ContactFormSection Shared Slice
 *
 * - **API ID**: `contact_form_section`
 * - **Description**: ContactFormSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactFormSectionSlice = prismic.SharedSlice<
  "contact_form_section",
  ContactFormSectionSliceVariation
>;

/**
 * Default variation for ContactInfoSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *ContactInfoSection*
 */
type ContactInfoSectionSliceVariation = ContactInfoSectionSliceDefault;

/**
 * ContactInfoSection Shared Slice
 *
 * - **API ID**: `contact_info_section`
 * - **Description**: ContactInfoSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactInfoSectionSlice = prismic.SharedSlice<
  "contact_info_section",
  ContactInfoSectionSliceVariation
>;

/**
 * Primary content in *Featured → Primary*
 */
export interface FeaturedSliceDefaultPrimary {
  /**
   * Heading field in *Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Button Label field in *Featured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Featured → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for Featured Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Featured*
 */
type FeaturedSliceVariation = FeaturedSliceDefault;

/**
 * Featured Shared Slice
 *
 * - **API ID**: `featured`
 * - **Description**: Featured
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedSlice = prismic.SharedSlice<
  "featured",
  FeaturedSliceVariation
>;

/**
 * Primary content in *Features → Primary*
 */
export interface FeaturesSliceDefaultPrimary {
  /**
   * Heading field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Features → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *Features → Items*
 */
export interface FeaturesSliceDefaultItem {
  /**
   * Card Heading field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_heading: prismic.KeyTextField;

  /**
   * Card Description field in *Features → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: features.items[].card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_description: prismic.KeyTextField;
}

/**
 * Default variation for Features Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturesSliceDefaultPrimary>,
  Simplify<FeaturesSliceDefaultItem>
>;

/**
 * Slice variation for *Features*
 */
type FeaturesSliceVariation = FeaturesSliceDefault;

/**
 * Features Shared Slice
 *
 * - **API ID**: `features`
 * - **Description**: Features
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturesSlice = prismic.SharedSlice<
  "features",
  FeaturesSliceVariation
>;

/**
 * Primary content in *FrequentAnsweredQuestions → Primary*
 */
export interface FrequentAnsweredQuestionsSliceDefaultPrimary {
  /**
   * Heading field in *FrequentAnsweredQuestions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequent_answered_questions.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *FrequentAnsweredQuestions → Items*
 */
export interface FrequentAnsweredQuestionsSliceDefaultItem {
  /**
   * Question field in *FrequentAnsweredQuestions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequent_answered_questions.items[].question
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  question: prismic.KeyTextField;

  /**
   * Answer field in *FrequentAnsweredQuestions → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: frequent_answered_questions.items[].answer
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  answer: prismic.KeyTextField;
}

/**
 * Default variation for FrequentAnsweredQuestions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentAnsweredQuestionsSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<FrequentAnsweredQuestionsSliceDefaultPrimary>,
    Simplify<FrequentAnsweredQuestionsSliceDefaultItem>
  >;

/**
 * Slice variation for *FrequentAnsweredQuestions*
 */
type FrequentAnsweredQuestionsSliceVariation =
  FrequentAnsweredQuestionsSliceDefault;

/**
 * FrequentAnsweredQuestions Shared Slice
 *
 * - **API ID**: `frequent_answered_questions`
 * - **Description**: FrequentAnsweredQuestions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FrequentAnsweredQuestionsSlice = prismic.SharedSlice<
  "frequent_answered_questions",
  FrequentAnsweredQuestionsSliceVariation
>;

/**
 * Primary content in *FullWidthFeatured → Primary*
 */
export interface FullWidthFeaturedSliceDefaultPrimary {
  /**
   * Heading field in *FullWidthFeatured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_featured.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *FullWidthFeatured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_featured.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Button Label field in *FullWidthFeatured → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_featured.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *FullWidthFeatured → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_featured.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for FullWidthFeatured Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthFeaturedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthFeaturedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthFeatured*
 */
type FullWidthFeaturedSliceVariation = FullWidthFeaturedSliceDefault;

/**
 * FullWidthFeatured Shared Slice
 *
 * - **API ID**: `full_width_featured`
 * - **Description**: FullWidthFeatured
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthFeaturedSlice = prismic.SharedSlice<
  "full_width_featured",
  FullWidthFeaturedSliceVariation
>;

/**
 * Primary content in *FullWidthQuote → Primary*
 */
export interface FullWidthQuoteSliceDefaultPrimary {
  /**
   * Quote field in *FullWidthQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_quote.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField;

  /**
   * Author field in *FullWidthQuote → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: full_width_quote.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Default variation for FullWidthQuote Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthQuoteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FullWidthQuoteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FullWidthQuote*
 */
type FullWidthQuoteSliceVariation = FullWidthQuoteSliceDefault;

/**
 * FullWidthQuote Shared Slice
 *
 * - **API ID**: `full_width_quote`
 * - **Description**: FullWidthQuote
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FullWidthQuoteSlice = prismic.SharedSlice<
  "full_width_quote",
  FullWidthQuoteSliceVariation
>;

/**
 * Primary content in *GoogleMapsSection → Primary*
 */
export interface GoogleMapsSectionSliceDefaultPrimary {
  /**
   * Heading field in *GoogleMapsSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: google_maps_section.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *GoogleMapsSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: google_maps_section.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for GoogleMapsSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GoogleMapsSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<GoogleMapsSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *GoogleMapsSection*
 */
type GoogleMapsSectionSliceVariation = GoogleMapsSectionSliceDefault;

/**
 * GoogleMapsSection Shared Slice
 *
 * - **API ID**: `google_maps_section`
 * - **Description**: GoogleMapsSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GoogleMapsSectionSlice = prismic.SharedSlice<
  "google_maps_section",
  GoogleMapsSectionSliceVariation
>;

/**
 * Primary content in *HeadingContent → Primary*
 */
export interface HeadingContentSliceDefaultPrimary {
  /**
   * Dark Background field in *HeadingContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: heading_content.primary.dark_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dark_background: prismic.BooleanField;

  /**
   * Heading field in *HeadingContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *HeadingContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: heading_content.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Small Width field in *HeadingContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: heading_content.primary.small_width
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  small_width: prismic.BooleanField;
}

/**
 * Default variation for HeadingContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeadingContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeadingContent*
 */
type HeadingContentSliceVariation = HeadingContentSliceDefault;

/**
 * HeadingContent Shared Slice
 *
 * - **API ID**: `heading_content`
 * - **Description**: HeadingContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadingContentSlice = prismic.SharedSlice<
  "heading_content",
  HeadingContentSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Button Link field in *Hero → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button Label field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *ImageContent → Primary*
 */
export interface ImageContentSliceDefaultPrimary {
  /**
   * Dark Background field in *ImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_content.primary.dark_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  dark_background: prismic.BooleanField;

  /**
   * Featured Image field in *ImageContent → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.featured_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featured_image: prismic.ImageField<never>;

  /**
   * Heading field in *ImageContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Content field in *ImageContent → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Button Label field in *ImageContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *ImageContent → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_content.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Need Button field in *ImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_content.primary.need_button
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  need_button: prismic.BooleanField;

  /**
   * Right Image field in *ImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_content.primary.right_image
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  right_image: prismic.BooleanField;

  /**
   * Green Background field in *ImageContent → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: image_content.primary.green_background
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  green_background: prismic.BooleanField;
}

/**
 * Default variation for ImageContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageContent*
 */
type ImageContentSliceVariation = ImageContentSliceDefault;

/**
 * ImageContent Shared Slice
 *
 * - **API ID**: `image_content`
 * - **Description**: ImageContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageContentSlice = prismic.SharedSlice<
  "image_content",
  ImageContentSliceVariation
>;

/**
 * Default variation for NewsletterSub Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSubSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *NewsletterSub*
 */
type NewsletterSubSliceVariation = NewsletterSubSliceDefault;

/**
 * NewsletterSub Shared Slice
 *
 * - **API ID**: `newsletter_sub`
 * - **Description**: NewsletterSub
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSubSlice = prismic.SharedSlice<
  "newsletter_sub",
  NewsletterSubSliceVariation
>;

/**
 * Primary content in *PageHero → Primary*
 */
export interface PageHeroSliceDefaultPrimary {
  /**
   * Heading field in *PageHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *PageHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_hero.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Hero Image field in *PageHero → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_hero.primary.hero_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Tag field in *PageHero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_hero.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;
}

/**
 * Default variation for PageHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PageHeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PageHero*
 */
type PageHeroSliceVariation = PageHeroSliceDefault;

/**
 * PageHero Shared Slice
 *
 * - **API ID**: `page_hero`
 * - **Description**: PageHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PageHeroSlice = prismic.SharedSlice<
  "page_hero",
  PageHeroSliceVariation
>;

/**
 * Primary content in *QuoteContent → Primary*
 */
export interface QuoteContentSliceDefaultPrimary {
  /**
   * Quote field in *QuoteContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_content.primary.quote
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  quote: prismic.KeyTextField;

  /**
   * Author field in *QuoteContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_content.primary.author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;

  /**
   * Tag field in *QuoteContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_content.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Heading field in *QuoteContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *QuoteContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: quote_content.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for QuoteContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<QuoteContentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *QuoteContent*
 */
type QuoteContentSliceVariation = QuoteContentSliceDefault;

/**
 * QuoteContent Shared Slice
 *
 * - **API ID**: `quote_content`
 * - **Description**: QuoteContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type QuoteContentSlice = prismic.SharedSlice<
  "quote_content",
  QuoteContentSliceVariation
>;

/**
 * Primary content in *RecommendedReading → Items*
 */
export interface RecommendedReadingSliceDefaultItem {
  /**
   * Article Heading field in *RecommendedReading → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_reading.items[].article_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article_heading: prismic.KeyTextField;

  /**
   * Article Description field in *RecommendedReading → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_reading.items[].article_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  article_description: prismic.KeyTextField;

  /**
   * Article Link field in *RecommendedReading → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: recommended_reading.items[].article_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  article_link: prismic.LinkField;
}

/**
 * Default variation for RecommendedReading Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommendedReadingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<RecommendedReadingSliceDefaultItem>
>;

/**
 * Slice variation for *RecommendedReading*
 */
type RecommendedReadingSliceVariation = RecommendedReadingSliceDefault;

/**
 * RecommendedReading Shared Slice
 *
 * - **API ID**: `recommended_reading`
 * - **Description**: RecommendedReading
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RecommendedReadingSlice = prismic.SharedSlice<
  "recommended_reading",
  RecommendedReadingSliceVariation
>;

/**
 * Primary content in *ReusableCardSlice → Primary*
 */
export interface ReusableCardSliceSliceDefaultPrimary {
  /**
   * Heading field in *ReusableCardSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_card_slice.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ReusableCardSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_card_slice.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *ReusableCardSlice → Items*
 */
export interface ReusableCardSliceSliceDefaultItem {
  /**
   * Card Heading field in *ReusableCardSlice → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_card_slice.items[].card_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_heading: prismic.KeyTextField;

  /**
   * Card Content field in *ReusableCardSlice → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_card_slice.items[].card_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  card_content: prismic.RichTextField;
}

/**
 * Default variation for ReusableCardSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReusableCardSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReusableCardSliceSliceDefaultPrimary>,
  Simplify<ReusableCardSliceSliceDefaultItem>
>;

/**
 * Slice variation for *ReusableCardSlice*
 */
type ReusableCardSliceSliceVariation = ReusableCardSliceSliceDefault;

/**
 * ReusableCardSlice Shared Slice
 *
 * - **API ID**: `reusable_card_slice`
 * - **Description**: ReusableCardSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReusableCardSliceSlice = prismic.SharedSlice<
  "reusable_card_slice",
  ReusableCardSliceSliceVariation
>;

/**
 * Primary content in *ReusableTableSlice → Primary*
 */
export interface ReusableTableSliceSliceDefaultPrimary {
  /**
   * Tag field in *ReusableTableSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_table_slice.primary.tag
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tag: prismic.KeyTextField;

  /**
   * Heading field in *ReusableTableSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_table_slice.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ReusableTableSlice → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusable_table_slice.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for ReusableTableSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReusableTableSliceSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReusableTableSliceSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ReusableTableSlice*
 */
type ReusableTableSliceSliceVariation = ReusableTableSliceSliceDefault;

/**
 * ReusableTableSlice Shared Slice
 *
 * - **API ID**: `reusable_table_slice`
 * - **Description**: ReusableTableSlice
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReusableTableSliceSlice = prismic.SharedSlice<
  "reusable_table_slice",
  ReusableTableSliceSliceVariation
>;

/**
 * Primary content in *ReusuableContent → Primary*
 */
export interface ReusuableContentSliceDefaultPrimary {
  /**
   * Heading field in *ReusuableContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusuable_content.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *ReusuableContent → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusuable_content.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *ReusuableContent → Items*
 */
export interface ReusuableContentSliceDefaultItem {
  /**
   * featuredImage field in *ReusuableContent → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reusuable_content.items[].featuredimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  featuredimage: prismic.ImageField<never>;

  /**
   * Image Heading field in *ReusuableContent → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusuable_content.items[].image_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  image_heading: prismic.KeyTextField;

  /**
   * Image Content field in *ReusuableContent → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reusuable_content.items[].image_content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  image_content: prismic.RichTextField;
}

/**
 * Default variation for ReusuableContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReusuableContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReusuableContentSliceDefaultPrimary>,
  Simplify<ReusuableContentSliceDefaultItem>
>;

/**
 * Slice variation for *ReusuableContent*
 */
type ReusuableContentSliceVariation = ReusuableContentSliceDefault;

/**
 * ReusuableContent Shared Slice
 *
 * - **API ID**: `reusuable_content`
 * - **Description**: ReusuableContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReusuableContentSlice = prismic.SharedSlice<
  "reusuable_content",
  ReusuableContentSliceVariation
>;

/**
 * Primary content in *Solutions → Primary*
 */
export interface SolutionsSliceDefaultPrimary {
  /**
   * Heading field in *Solutions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Solutions → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: solutions.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Default variation for Solutions Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SolutionsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Solutions*
 */
type SolutionsSliceVariation = SolutionsSliceDefault;

/**
 * Solutions Shared Slice
 *
 * - **API ID**: `solutions`
 * - **Description**: Solutions
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SolutionsSlice = prismic.SharedSlice<
  "solutions",
  SolutionsSliceVariation
>;

/**
 * Primary content in *Stats → Primary*
 */
export interface StatsSliceDefaultPrimary {
  /**
   * Heading field in *Stats → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Stats → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;

  /**
   * Button Label field in *Stats → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button Link field in *Stats → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *Stats → Items*
 */
export interface StatsSliceDefaultItem {
  /**
   * Circle Number field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.items[].circle_number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  circle_number: prismic.KeyTextField;

  /**
   * Circle Heading field in *Stats → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stats.items[].circle_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  circle_heading: prismic.KeyTextField;
}

/**
 * Default variation for Stats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StatsSliceDefaultPrimary>,
  Simplify<StatsSliceDefaultItem>
>;

/**
 * Slice variation for *Stats*
 */
type StatsSliceVariation = StatsSliceDefault;

/**
 * Stats Shared Slice
 *
 * - **API ID**: `stats`
 * - **Description**: Stats
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type StatsSlice = prismic.SharedSlice<"stats", StatsSliceVariation>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Heading field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Tagline field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.tagline
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  tagline: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Name field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Review field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].review
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  review: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TextBlock → Primary*
 */
export interface TextBlockSliceDefaultPrimary {
  /**
   * Content field in *TextBlock → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_block.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for TextBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlockSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TextBlock*
 */
type TextBlockSliceVariation = TextBlockSliceDefault;

/**
 * TextBlock Shared Slice
 *
 * - **API ID**: `text_block`
 * - **Description**: TextBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextBlockSlice = prismic.SharedSlice<
  "text_block",
  TextBlockSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogpostDocument,
      BlogpostDocumentData,
      BlogpostDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      ServiceDocument,
      ServiceDocumentData,
      ServiceDocumentDataSlicesSlice,
      AllDocumentTypes,
      BlogIndexSlice,
      BlogIndexSliceVariation,
      BlogIndexSliceDefault,
      CheckImageContentSlice,
      CheckImageContentSliceDefaultPrimary,
      CheckImageContentSliceDefaultItem,
      CheckImageContentSliceVariation,
      CheckImageContentSliceDefault,
      ContactFormSectionSlice,
      ContactFormSectionSliceVariation,
      ContactFormSectionSliceDefault,
      ContactInfoSectionSlice,
      ContactInfoSectionSliceVariation,
      ContactInfoSectionSliceDefault,
      FeaturedSlice,
      FeaturedSliceDefaultPrimary,
      FeaturedSliceVariation,
      FeaturedSliceDefault,
      FeaturesSlice,
      FeaturesSliceDefaultPrimary,
      FeaturesSliceDefaultItem,
      FeaturesSliceVariation,
      FeaturesSliceDefault,
      FrequentAnsweredQuestionsSlice,
      FrequentAnsweredQuestionsSliceDefaultPrimary,
      FrequentAnsweredQuestionsSliceDefaultItem,
      FrequentAnsweredQuestionsSliceVariation,
      FrequentAnsweredQuestionsSliceDefault,
      FullWidthFeaturedSlice,
      FullWidthFeaturedSliceDefaultPrimary,
      FullWidthFeaturedSliceVariation,
      FullWidthFeaturedSliceDefault,
      FullWidthQuoteSlice,
      FullWidthQuoteSliceDefaultPrimary,
      FullWidthQuoteSliceVariation,
      FullWidthQuoteSliceDefault,
      GoogleMapsSectionSlice,
      GoogleMapsSectionSliceDefaultPrimary,
      GoogleMapsSectionSliceVariation,
      GoogleMapsSectionSliceDefault,
      HeadingContentSlice,
      HeadingContentSliceDefaultPrimary,
      HeadingContentSliceVariation,
      HeadingContentSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      ImageContentSlice,
      ImageContentSliceDefaultPrimary,
      ImageContentSliceVariation,
      ImageContentSliceDefault,
      NewsletterSubSlice,
      NewsletterSubSliceVariation,
      NewsletterSubSliceDefault,
      PageHeroSlice,
      PageHeroSliceDefaultPrimary,
      PageHeroSliceVariation,
      PageHeroSliceDefault,
      QuoteContentSlice,
      QuoteContentSliceDefaultPrimary,
      QuoteContentSliceVariation,
      QuoteContentSliceDefault,
      RecommendedReadingSlice,
      RecommendedReadingSliceDefaultItem,
      RecommendedReadingSliceVariation,
      RecommendedReadingSliceDefault,
      ReusableCardSliceSlice,
      ReusableCardSliceSliceDefaultPrimary,
      ReusableCardSliceSliceDefaultItem,
      ReusableCardSliceSliceVariation,
      ReusableCardSliceSliceDefault,
      ReusableTableSliceSlice,
      ReusableTableSliceSliceDefaultPrimary,
      ReusableTableSliceSliceVariation,
      ReusableTableSliceSliceDefault,
      ReusuableContentSlice,
      ReusuableContentSliceDefaultPrimary,
      ReusuableContentSliceDefaultItem,
      ReusuableContentSliceVariation,
      ReusuableContentSliceDefault,
      SolutionsSlice,
      SolutionsSliceDefaultPrimary,
      SolutionsSliceVariation,
      SolutionsSliceDefault,
      StatsSlice,
      StatsSliceDefaultPrimary,
      StatsSliceDefaultItem,
      StatsSliceVariation,
      StatsSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextBlockSlice,
      TextBlockSliceDefaultPrimary,
      TextBlockSliceVariation,
      TextBlockSliceDefault,
    };
  }
}
