// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_index: dynamic(() => import("./BlogIndex")),
  check_image_content: dynamic(() => import("./CheckImageContent")),
  contact_form_section: dynamic(() => import("./ContactFormSection")),
  contact_info_section: dynamic(() => import("./ContactInfoSection")),
  featured: dynamic(() => import("./Featured")),
  features: dynamic(() => import("./Features")),
  frequent_answered_questions: dynamic(
    () => import("./FrequentAnsweredQuestions"),
  ),
  full_width_featured: dynamic(() => import("./FullWidthFeatured")),
  full_width_quote: dynamic(() => import("./FullWidthQuote")),
  google_maps_section: dynamic(() => import("./GoogleMapsSection")),
  heading_content: dynamic(() => import("./HeadingContent")),
  hero: dynamic(() => import("./Hero")),
  image_content: dynamic(() => import("./ImageContent")),
  newsletter_sub: dynamic(() => import("./NewsletterSub")),
  page_hero: dynamic(() => import("./PageHero")),
  recommended_reading: dynamic(() => import("./RecommendedReading")),
  reusable_card_slice: dynamic(() => import("./ReusableCardSlice")),
  reusuable_content: dynamic(() => import("./ReusuableContent")),
  solutions: dynamic(() => import("./Solutions")),
  stats: dynamic(() => import("./Stats")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_block: dynamic(() => import("./TextBlock")),
};
